# Generated by Django 5.2.17 on 2026-09-26 14:48

import django.db.models.deletion
import durc.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Soggetto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codice_fiscale', models.CharField(db_index=True, max_length=16, unique=True, verbose_name='Codice fiscale')),
                ('partita_iva', models.CharField(blank=True, db_index=True, max_length=11, verbose_name='Partita IVA')),
                ('denominazione', models.CharField(blank=True, db_index=True, max_length=255)),
                ('note', models.TextField(blank=True)),
                ('creato_il', models.DateTimeField(auto_now_add=True)),
                ('aggiornato_il', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Soggetto',
                'verbose_name_plural': 'Soggetti',
                'ordering': ['denominazione', 'codice_fiscale'],
            },
        ),
        migrations.CreateModel(
            name='Durc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('protocollo', models.CharField(blank=True, db_index=True, max_length=100)),
                ('denominazione', models.CharField(blank=True, max_length=255)),
                ('data_documento', models.DateField(blank=True, null=True)),
                ('data_scadenza', models.DateField(blank=True, db_index=True, null=True)),
                ('stato', models.CharField(choices=[('REGOLARE', 'Regolare'), ('IRREGOLARE', 'Non regolare'), ('NON_EFFETTUABILE', 'Verifica non effettuabile'), ('SCONOSCIUTO', 'Stato non determinato')], db_index=True, default='SCONOSCIUTO', max_length=25)),
                ('esito_inps', models.SmallIntegerField(blank=True, choices=[(0, 'Regolare'), (1, 'Irregolare'), (2, 'Non effettuabile')], null=True)),
                ('esito_inail', models.SmallIntegerField(blank=True, choices=[(0, 'Regolare'), (1, 'Irregolare'), (2, 'Non effettuabile')], null=True)),
                ('esito_cassa_edile', models.SmallIntegerField(blank=True, choices=[(0, 'Regolare'), (1, 'Irregolare'), (2, 'Non effettuabile')], null=True)),
                ('pdf', models.FileField(blank=True, upload_to=durc.models.durc_pdf_path)),
                ('pdf_sha256', models.CharField(blank=True, max_length=64)),
                ('pdnd_request_id', models.CharField(blank=True, max_length=255)),
                ('http_status', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('acquisito_il', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('note', models.TextField(blank=True)),
                ('richiesto_da', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='durc_richiesti', to=settings.AUTH_USER_MODEL)),
                ('soggetto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='durc', to='durc.soggetto')),
            ],
            options={
                'verbose_name': 'DURC',
                'verbose_name_plural': 'DURC',
                'ordering': ['-acquisito_il'],
            },
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('azione', models.CharField(choices=[('RICERCA', 'Ricerca'), ('CONSULTAZIONE_PDND', 'Consultazione PDND'), ('DOWNLOAD_PDF', 'Download PDF'), ('VISUALIZZAZIONE', 'Visualizzazione DURC'), ('MODIFICA', 'Modifica'), ('ALTRO', 'Altro')], db_index=True, max_length=30)),
                ('indirizzo_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('dettagli', models.JSONField(blank=True, default=dict)),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('utente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('durc', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='durc.durc')),
                ('soggetto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='durc.soggetto')),
            ],
            options={
                'verbose_name': 'Log attività',
                'verbose_name_plural': 'Log attività',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.AddIndex(
            model_name='durc',
            index=models.Index(fields=['soggetto', '-acquisito_il'], name='durc_durc_soggett_0523ea_idx'),
        ),
        migrations.AddIndex(
            model_name='durc',
            index=models.Index(fields=['stato', 'data_scadenza'], name='durc_durc_stato_45de3a_idx'),
        ),
    ]
