# Generated by Django 5.2.17 on 2026-09-26 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('durc', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfigurazionePDND',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(default='Configurazione principale', max_length=100)),
                ('client_id', models.CharField(blank=True, max_length=255)),
                ('purpose_id', models.CharField(blank=True, max_length=255, verbose_name='Purpose ID')),
                ('kid', models.CharField(blank=True, max_length=255, verbose_name='KID')),
                ('audience', models.CharField(blank=True, max_length=500)),
                ('url_autenticazione', models.URLField(blank=True, max_length=500)),
                ('url_servizio_durc', models.URLField(blank=True, max_length=500)),
                ('versione_eservice', models.CharField(blank=True, max_length=100, verbose_name='Versione e-service')),
                ('percorso_chiave_privata', models.CharField(default='/run/secrets/pdnd_private_key.pem', help_text='Percorso interno al container. La chiave non viene salvata nel database.', max_length=500)),
                ('attiva', models.BooleanField(default=False)),
                ('aggiornato_il', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Configurazione PDND',
                'verbose_name_plural': 'Configurazione PDND',
            },
        ),
    ]
