# Generated by Django 5.2.17 on 2026-09-26 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('durc', '0002_configurazionepdnd'),
    ]

    operations = [
        migrations.AddField(
            model_name='configurazionepdnd',
            name='alg',
            field=models.CharField(default='RS256', max_length=20, verbose_name='Algoritmo (alg)'),
        ),
        migrations.AddField(
            model_name='configurazionepdnd',
            name='aud',
            field=models.CharField(blank=True, max_length=500, verbose_name='Audience autenticazione (aud)'),
        ),
        migrations.AddField(
            model_name='configurazionepdnd',
            name='iss',
            field=models.CharField(blank=True, max_length=255, verbose_name='Issuer (iss)'),
        ),
        migrations.AddField(
            model_name='configurazionepdnd',
            name='sub',
            field=models.CharField(blank=True, max_length=255, verbose_name='Subject (sub)'),
        ),
        migrations.AddField(
            model_name='configurazionepdnd',
            name='typ',
            field=models.CharField(default='JWT', max_length=20, verbose_name='Tipo token (typ)'),
        ),
    ]
