# Generated by Django 5.2.17 on 2026-09-26 23:07

import durc.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('durc', '0003_configurazionepdnd_alg_configurazionepdnd_aud_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='durc',
            name='pdf',
            field=models.FileField(blank=True, storage=durc.models.durc_pdf_storage, upload_to=durc.models.durc_pdf_path),
        ),
    ]
