# Generated by Django 5.2.17 on 2026-09-27 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('durc', '0004_alter_durc_pdf'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfigurazioneEnte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_applicazione', models.CharField(default='Servizi Imprese', max_length=150, verbose_name='Nome applicazione')),
                ('sottotitolo_applicazione', models.CharField(blank=True, default='Consultazione DURC e Registro Imprese', max_length=255, verbose_name='Sottotitolo applicazione')),
                ('descrizione_applicazione', models.TextField(blank=True, verbose_name='Descrizione applicazione')),
                ('nome_ente', models.CharField(max_length=255, verbose_name='Nome ente')),
                ('nome_breve_ente', models.CharField(blank=True, max_length=100, verbose_name='Nome breve ente')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='ente/', verbose_name='Logo ente')),
                ('sito_istituzionale', models.URLField(blank=True, verbose_name='Sito istituzionale')),
                ('codice_fiscale', models.CharField(blank=True, max_length=16, verbose_name='Codice fiscale')),
                ('partita_iva', models.CharField(blank=True, max_length=11, verbose_name='Partita IVA')),
                ('codice_ipa', models.CharField(blank=True, max_length=50, verbose_name='Codice IPA')),
                ('codice_univoco_ufficio', models.CharField(blank=True, max_length=20, verbose_name='Codice univoco ufficio')),
                ('indirizzo', models.CharField(blank=True, max_length=255, verbose_name='Indirizzo')),
                ('cap', models.CharField(blank=True, max_length=10, verbose_name='CAP')),
                ('comune', models.CharField(blank=True, max_length=100, verbose_name='Comune')),
                ('provincia', models.CharField(blank=True, max_length=100, verbose_name='Provincia')),
                ('pec', models.EmailField(blank=True, max_length=254, verbose_name='PEC')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('telefono', models.CharField(blank=True, max_length=50, verbose_name='Telefono')),
                ('url_privacy', models.URLField(blank=True, verbose_name='Privacy')),
                ('url_cookie', models.URLField(blank=True, verbose_name='Cookie policy')),
                ('url_accessibilita', models.URLField(blank=True, verbose_name='Dichiarazione di accessibilità')),
                ('url_note_legali', models.URLField(blank=True, verbose_name='Note legali')),
                ('url_amministrazione_trasparente', models.URLField(blank=True, verbose_name='Amministrazione trasparente')),
                ('url_albo_pretorio', models.URLField(blank=True, verbose_name='Albo pretorio')),
                ('testo_footer', models.TextField(blank=True, verbose_name='Testo aggiuntivo footer')),
                ('aggiornato_il', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Configurazione ente',
                'verbose_name_plural': 'Configurazione ente',
            },
        ),
    ]
