# Generated by Django 5.2.17 on 2026-09-27 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('durc', '0005_configurazioneente'),
    ]

    operations = [
        migrations.AlterField(
            model_name='configurazioneente',
            name='nome_applicazione',
            field=models.CharField(max_length=150, verbose_name='Nome applicazione'),
        ),
        migrations.AlterField(
            model_name='configurazioneente',
            name='sottotitolo_applicazione',
            field=models.CharField(blank=True, max_length=255, verbose_name='Sottotitolo applicazione'),
        ),
    ]
