# Generated by Django 5.2.17 on 2026-09-27 09:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('durc', '0006_alter_configurazioneente_nome_applicazione_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='configurazioneente',
            name='logo',
        ),
    ]
