# Generated by Django 5.2.17 on 2026-09-27 10:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('durc', '0007_remove_configurazioneente_logo'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfigurazioneRegistroImprese',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(default='Configurazione principale', max_length=100)),
                ('ambiente', models.CharField(choices=[('COLLAUDO', 'Collaudo'), ('PRODUZIONE', 'Produzione')], default='PRODUZIONE', max_length=20)),
                ('client_id', models.CharField(blank=True, max_length=255, verbose_name='Client ID')),
                ('purpose_id', models.CharField(blank=True, max_length=255, verbose_name='Purpose ID')),
                ('kid', models.CharField(blank=True, max_length=255, verbose_name='KID')),
                ('alg', models.CharField(default='RS256', max_length=20, verbose_name='Algoritmo (alg)')),
                ('typ', models.CharField(default='JWT', max_length=20, verbose_name='Tipo token (typ)')),
                ('iss', models.CharField(blank=True, max_length=255, verbose_name='Issuer (iss)')),
                ('sub', models.CharField(blank=True, max_length=255, verbose_name='Subject (sub)')),
                ('aud', models.CharField(blank=True, max_length=500, verbose_name='Audience autenticazione (aud)')),
                ('audience', models.CharField(blank=True, max_length=500, verbose_name='Audience e-service')),
                ('url_autenticazione', models.URLField(blank=True, max_length=500, verbose_name='URL autenticazione PDND')),
                ('url_base_servizio', models.URLField(blank=True, help_text='Esempio produzione: https://pdnd.registroimprese.it', max_length=500, verbose_name='URL base Registro Imprese')),
                ('percorso_chiave_privata', models.CharField(default='/run/secrets/pdnd_private_key.pem', help_text='Percorso interno al container. La chiave non viene salvata nel database.', max_length=500)),
                ('timeout_secondi', models.PositiveSmallIntegerField(default=30, verbose_name='Timeout HTTP (secondi)')),
                ('attiva', models.BooleanField(default=False)),
                ('ultimo_voucher_ok', models.DateTimeField(blank=True, editable=False, null=True, verbose_name='Ultimo voucher ottenuto')),
                ('ultima_chiamata_ok', models.DateTimeField(blank=True, editable=False, null=True, verbose_name='Ultima chiamata riuscita')),
                ('ultimo_errore', models.TextField(blank=True, editable=False, verbose_name='Ultimo errore')),
                ('aggiornato_il', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Configurazione Registro Imprese',
                'verbose_name_plural': 'Configurazione Registro Imprese',
            },
        ),
        migrations.CreateModel(
            name='VisuraRegistroImprese',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('denominazione', models.CharField(blank=True, max_length=255)),
                ('codice_fiscale', models.CharField(blank=True, db_index=True, max_length=16)),
                ('partita_iva', models.CharField(blank=True, db_index=True, max_length=11)),
                ('cciaa', models.CharField(blank=True, max_length=10, verbose_name='CCIAA')),
                ('numero_rea', models.CharField(blank=True, db_index=True, max_length=20, verbose_name='Numero REA')),
                ('forma_giuridica', models.CharField(blank=True, max_length=255)),
                ('stato_impresa', models.CharField(blank=True, max_length=100)),
                ('pec', models.EmailField(blank=True, db_index=True, max_length=254, verbose_name='PEC')),
                ('sede_comune', models.CharField(blank=True, max_length=150)),
                ('sede_provincia', models.CharField(blank=True, max_length=10)),
                ('sede_toponimo', models.CharField(blank=True, max_length=100)),
                ('sede_via', models.CharField(blank=True, max_length=255)),
                ('sede_civico', models.CharField(blank=True, max_length=50)),
                ('sede_cap', models.CharField(blank=True, max_length=10)),
                ('sede_frazione', models.CharField(blank=True, max_length=150)),
                ('sede_stato', models.CharField(blank=True, max_length=150)),
                ('xml_originale', models.TextField()),
                ('http_status', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('pdnd_request_id', models.CharField(blank=True, max_length=255)),
                ('acquisito_il', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('note', models.TextField(blank=True)),
                ('richiesto_da', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='visure_registro_imprese_richieste', to=settings.AUTH_USER_MODEL)),
                ('soggetto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='visure_registro_imprese', to='durc.soggetto')),
            ],
            options={
                'verbose_name': 'Acquisizione Registro Imprese',
                'verbose_name_plural': 'Acquisizioni Registro Imprese',
                'ordering': ['-acquisito_il'],
                'indexes': [models.Index(fields=['soggetto', '-acquisito_il'], name='durc_visura_soggett_764635_idx')],
            },
        ),
    ]
