# Generated by Django 5.2.17 on 2026-09-28 19:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('durc', '0009_durc_risposta_inps'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='auditlog',
            options={'ordering': ['-timestamp'], 'verbose_name': 'Log DURC', 'verbose_name_plural': 'Log DURC'},
        ),
        migrations.AlterModelOptions(
            name='visuraregistroimprese',
            options={'ordering': ['-acquisito_il'], 'verbose_name': 'Log Registro Imprese', 'verbose_name_plural': 'Log Registro Imprese'},
        ),
    ]
