# Generated by Django 5.2.17 on 2026-09-28 19:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('durc', '0010_alter_auditlog_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='configurazionepdnd',
            options={'verbose_name': 'Configurazione DURC', 'verbose_name_plural': 'Configurazione DURC'},
        ),
    ]
