# Generated by Django 5.2.17 on 2026-09-28 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('durc', '0011_alter_configurazionepdnd_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='configurazioneente',
            name='max_pdf_durc_per_soggetto',
            field=models.PositiveIntegerField(default=10, help_text='Numero massimo di PDF DURC conservati fisicamente per ciascun soggetto. Lo storico dei record DURC rimane comunque nel database.', verbose_name='Numero massimo PDF DURC per soggetto'),
        ),
    ]
